package officeHour.quizPreparation;

public class TryException {
    public static void main(String[] args) {
        /*
    try{
        int[] arr = new int[1];
        arr[1] = 5;
    }
    catch (Exception e){
        System.out.print("A");
    }
    catch (RuntimeException e){
            System.out.print("B");
    }
    catch (ArrayIndexOutOfBoundsException e){
        System.out.print("C");
    }*/
    }

}
